### ISSUE TITLE
Set Github Action to automatically refresh data

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-data-transformation#11]
Create a script so that what we are currently running manually to refresh the data can be done automatically, once a month (while still keeping the manual refresh Github Action).

**Comment by maxachis** [comment]
I create this issue and I assign it to myself!

**Comment by hellonewman** [comment]
Max did this- chec back Nov 1

**Comment by maxachis** [comment]
This works! Just a month delayed in closing it.
