### ISSUE TITLE
Stakeholder meeting

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-data-transformation#12]
Set up meeting with stakeholders to review!

**Comment by hellonewman** [comment]
Dec 21st, 1-2:30pm

**Comment by hellonewman** [comment]
Link to join: https://us02web.zoom.us/meeting/register/tZUoduuurjwtEtFgy47jIlxlnA_0c6vsBDy7

We will likely be early in the agenda, and there's no need to stay beyond our piece.

**Comment by hellonewman** [comment]
the stakeholder meeting got moved to Wed Dec 7. Our part will be at 3pm. Registration link if you want to attend: https://us02web.zoom.us/meeting/register/tZUoduuurjwtEtFgy47jIlxlnA_0c6vsBDy7

**Comment by maxachis** [comment]
Stakeholder meeting has come and gone, so this can be closed!
