### ISSUE TITLE
Slides for stakeholder meeting

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-data-transformation#17]
Should outline:
- each data source and what it contains
- where map lives and basic technical details
- updates: automatic and user-submitted
- workflow for reviewing user submitted food sites
- map demo including: address search, filtering by type/services, radius slider, and adding a new location thru the online form

**Comment by maxachis** [comment]
Stakeholder meeting has come and gone, so this can be closed!
