### ISSUE TITLE
Add logic for seasonal summer meal site and farmer's market displays

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-data-transformation#20]
Summer meal sites and farmer's markets (except Bloomfield Farmer's Market) are not available at all times of the year, and it makes sense to not have that information showing at times of the year when no one could go to thos.

We need to change the logic on the backend so that when Summer Meal Sites are not in season (and they're in season between June and August), they are not displayed, and the same for non-Bloomfield Farmer's Markets (whose season is variable but tends to be between Mother's Day and November)

**Comment by maxachis** [comment]
Larry has opened a pull request on this! #23

**Comment by runstache** [comment]
Merged
