### ISSUE TITLE
Changes to Info page of map

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-data-transformation#4]
See slide 4 for details! https://docs.google.com/presentation/d/1ktVrZegMr6E6Fi3PgSDvq6ntIqsuMxZD5vbt6mH19Ow/

**Comment by hellonewman** [comment]
move

**Comment by maxachis** [comment]
Everything but what is described in #16 is done, so closing this for cleanliness' sake 🧼🧼🧼
