### ISSUE TITLE
Ensure website is mobile-friendly

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-data-transformation#6]
Most of our development has been done on desktop. It's entirely possible everything works well out of the box on mobile, but in either case we should check and confirm this.

**Comment by runstache** [comment]
One of the things that we might want to investigate is moving the navigation from the side to the top.  When building things for mobile, it's normally best to keep things off the Left and Right of the screen to maximize the real estate of the map.  We could move the navigation sections to the top using bootstrap and have the map be below for scrolling.

**Comment by maxachis** [comment]
We probably want to specify what changes we want, and compare them to how things look right now. Once we have a specific idea of how we want everything to look, it'll be easier for someone to work on it.

Here is the main page when configured for "IPad Air"
![image](https://user-images.githubusercontent.com/48846180/173940960-2ee56bfd-3a30-4b83-9170-02b28476f59c.png)

Here's how it looks for "Samsung Galaxy S8"
![image](https://user-images.githubusercontent.com/48846180/173941024-6b56526f-1eca-4ae9-872a-47a5e4698f6c.png)

Here's how it looks for "iPhone SE"
![image](https://user-images.githubusercontent.com/48846180/173941115-28de30bd-c4f5-4512-b5bc-242440308787.png)

**Comment by maxachis** [comment]
There was a request to move the navigation buttons (plus, minus, arrow thingy) from top-right to bottom-right, and someone MIGHT have made those changes locally, but we don't have a pull request for that right now.

**Comment by maxachis** [comment]
[Michael Feeney](https://github.com/mike-feeney) is getting close to done with this -- there's just a bug that needs to be fixed with how the lower bar appears. Here's how it looks right now!

![image](https://user-images.githubusercontent.com/48846180/180094113-8371750c-8407-4157-adee-1254f91f7871.png)

And here is Mike's repository/branch:
https://github.com/mike-feeney/CodeForPittsburgh.github.io/tree/mobile-debug

**Comment by maxachis** [comment]
[Giovanni](https://github.com/gsvevo) will also be helping out Mike with this!

**Comment by maxachis** [comment]
Mike says it's ready for production, although with one caveat:

Only issue is that the sidebar, while it opens smoothly, just closes abruptly when you collapse it. No immediately apparent easy way to solve this, but it's such a minor issue that trying to solve it is likely more trouble than it's worth.

**Comment by hellonewman** [comment]
all done!
