### ISSUE TITLE
 When clicking filter, should that change what results are already on the results page?

### ISSUE THREAD

**Issue by maxachis** [CodeForPittsburgh/food-access-data-transformation#7]

**Comment by hellonewman** [comment]
Yes it should.

**Comment by maxachis** [comment]
Can confirm this is still an active issue that needs addressed.

**Comment by maxachis** [comment]
Mike says he fixed that in his latest pull request, which we'll work on actually pulling! 

Mike: I had to change the functions a little bit, generalizing them so that the listener that listens for the toggles and the listener that listens for the map click now can work together whereas before they were on independent tracks.

**Comment by hellonewman** [comment]
it does not!

**Comment by hellonewman** [comment]
it does NOW :)
