### ISSUE TITLE
Remove Home page of food access map; default to the Search page

### ISSUE THREAD

**Issue by hellonewman** [CodeForPittsburgh/food-access-data-transformation#8]
See slide 1 of https://docs.google.com/presentation/d/1ktVrZegMr6E6Fi3PgSDvq6ntIqsuMxZD5vbt6mH19Ow/ for details!

**Comment by maxachis** [comment]
@mike-feeney has an pull request in the pipeline for this that hasn't yet been made into an official pull request, so this is _very_ close to being done.

**Comment by maxachis** [comment]
Pull request made, so this is done! 🍾
